name: build-and-release
run-name: Build/release/publish streamlit-jdgrid
on:
    push:
        branches:
            - 'test-**'
    release:
        types: [published]

env:
    NODE_VERSION: 21.x
    PYTHON_BUILD_VERSION: 1.0.3
    PYTHON_TWINE_VERSION: 4.0.2
    PYTHON_VERSION: 3.8

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Install git
              run: sudo apt-get update && sudo apt-get install git -y
            - uses: actions/checkout@v4
            - name: Set up Python ${{ env.PYTHON_VERSION }}
              uses: actions/setup-python@v5
              with:
                  python-version: ${{ env.PYTHON_VERSION }}
            - name: Set up Node ${{ env.NODE_VERSION }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ env.NODE_VERSION }}
            - name: Install build deps
              working-directory: ./st_aggrid
              run: pip install build==${{ env.PYTHON_BUILD_VERSION }} && npm install --workspaces false
            - name: Perform build
              run: npm run build

