name: build-and-release
run-name: Build/release/publish streamlit-jdgrid
on:
    push:
        branches:
            - 'test-**'
    release:
        types: [published]

env:
    NODE_VERSION: 20.x
    PYTHON_BUILD_VERSION: 1.0.3
    PYTHON_TWINE_VERSION: 4.0.2
    PYTHON_VERSION: 3.8

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Install git
              run: apt update && apt install git -y
            - uses: actions/checkout@v5
            - name: Set up Python ${{ env.PYTHON_VERSION }}
              uses: actions/setup-python@v4
              with:
                  python-version: ${{ env.PYTHON_VERSION }}
            - name: Set up Node ${{ env.NODE_VERSION }}
              uses: actions/setup-node@v4
              with:
                  python-version: ${{ env.NODE_VERSION }}
            - name: Install Python build deps
              run: pip install build==${{ env.PYTHON_BUILD_VERSION }} twine==${{ env.PYTHON_TWINE_VERSION }}

